name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Patch for missing sg13g2_io.v
      - name: Fix missing sg13g2_io.v
        run: |
          mkdir -p /home/runner/pdk/ihp-sg13g2/libs.ref/sg13g2_io/verilog
          find /home/runner/pdk/ihp-sg13g2 -name sg13g2_io.v -exec cp {} /home/runner/pdk/ihp-sg13g2/libs.ref/sg13g2_io/verilog/ \; || true
          ls -l /home/runner/pdk/ihp-sg13g2/libs.ref/sg13g2_io/verilog

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky25a
        with:
          pdk: sky130

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttsky25a
        with:
          pdk: sky130
